### ISSUE TITLE
Error on username input

### ISSUE THREAD

**Issue by Ukraine1449** [RuadhanKM/WilsonLanChatroom#1]
Username: Ukraine
Starting up on 10.167.134.241 port 10000
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Sublime Text 3\thingy.py", line 15, in AcceptMessage
    sock1.bind(server_address)
OSError: [WinError 10049] The requested address is not valid in its context

**Comment by RuadhanKM** [comment]
Change ip on line 10 via the 'ipconfig' command in command prompt. (under ipv4)

**Comment by Ukraine1449** [comment]
already tried.
